# Generated by Django 5.1.7 on 2025-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('specialty', models.CharField(choices=[('frontend', 'Frontend-разработка'), ('backend', 'Backend-разработка'), ('data_science', 'Data Science'), ('devops', 'DevOps'), ('other', 'Другое')], default='frontend', max_length=20, verbose_name='Специальность')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Оценка сайту (1–10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
